import {products} from '../data/mock'
import type {AdminArchiveItem,AdminAudit,AdminEmployee,AdminNotification,AdminOrderUpdate,AdminPurchase,AdminSession,AdminSettings,AdminSupplier} from '../types/admin'
import type {ProOrder,ProSav} from '../types/employee'
import {employeeInventoryService,employeeMessagingService,employeeOrdersService,employeePosService,employeeSavService} from './employee'
import {storage} from './storage'

const key={session:'er-admin-session',employees:'er-admin-employees',suppliers:'er-admin-suppliers',purchases:'er-admin-purchases',notes:'er-admin-notifications',audit:'er-admin-audit',archive:'er-admin-archive',settings:'er-admin-settings'}
const now=()=>new Date().toLocaleString('fr-MA')
const seedEmployees:AdminEmployee[]=[
 {id:'emp-a',firstName:'Amina',lastName:'Rachid',role:'Vendeuse',phone:'+212 6 12 34 56 78',email:'amina@electrorachid.ma',active:true,lastLogin:'Aujourd’hui · 08:41',permissions:['orders']},
 {id:'emp-b',firstName:'Youssef',lastName:'El Mansouri',role:'Polyvalent',phone:'+212 6 44 10 20 30',email:'youssef@electrorachid.ma',active:true,lastLogin:'Aujourd’hui · 09:05',permissions:['products_view','stock_view','stock_edit','pos']},
 {id:'emp-c',firstName:'Salma',lastName:'Bennani',role:'SAV',phone:'+212 6 55 40 61 82',email:'salma@electrorachid.ma',active:true,lastLogin:'Hier · 17:52',permissions:['sav']}
]
const seedSuppliers:AdminSupplier[]=[{id:'sup-1',name:'Atlas Équipement',contact:'Karim B.',phone:'+212 5 22 40 10 80',email:'contact@atlas-equipement.ma',active:true,products:12},{id:'sup-2',name:'Maison & Cuisine',contact:'Nora H.',phone:'+212 5 22 64 30 10',email:'pro@maisoncuisine.ma',active:true,products:8}]
const seedPurchases:AdminPurchase[]=[{id:'ACH-2026-048',supplierId:'sup-1',date:'01/10/2026',total:18450,status:'received',lines:[{productId:'af55',quantity:20,cost:760}]},{id:'ACH-2026-049',supplierId:'sup-2',date:'03/10/2026',total:6240,status:'ordered',lines:[{productId:'st24',quantity:12,cost:420}]}]
const defaultSettings:AdminSettings={storeName:'Electro Rachid',phone:'+212 5 22 00 11 22',whatsapp:'+212 6 00 00 00 00',address:'Ain Al Aouda, Maroc',hours:'Lun. – Sam. · 09:00 – 19:00',heroTitle:'L’équipement qui simplifie votre quotidien',heroText:'Une sélection fiable pour la cuisine et la maison.',primaryColor:'#163f3a'}
const audit=(action:string,entity:string)=>{const item:AdminAudit={id:crypto.randomUUID(),actor:'Rachid Admin',action,entity,date:now()};storage.set(key.audit,[item,...storage.get<AdminAudit[]>(key.audit,[])])}

export const adminAuthService={get:()=>storage.get<AdminSession|null>(key.session,null),login:(first:string,last:string,password:string)=>{if(first.trim().toLowerCase()!=='rachid'||last.trim().toLowerCase()!=='admin'||password!=='ER-ADMIN-2026')return null;const session:AdminSession={id:'admin-1',firstName:'Rachid',lastName:'Admin',role:'administrator'};storage.set(key.session,session);audit('Connexion à','Administration');return session},logout:()=>{audit('Déconnexion de','Administration');storage.remove(key.session)}}
export const adminDashboardService={get:()=>{const orders=employeeOrdersService.all();const stock=employeeInventoryService.get();const sales=employeePosService.all();return {revenue:orders.filter(o=>o.status!=='cancelled').reduce((sum,o)=>sum+o.total,0)+sales.reduce((sum,o)=>sum+o.total,0),orders:orders.length,average:orders.length?Math.round(orders.reduce((sum,o)=>sum+o.total,0)/orders.length):0,pending:orders.filter(o=>['new','confirmed','preparing'].includes(o.status)).length,low:products.filter(p=>(stock[p.id]??0)<5).length,out:products.filter(p=>(stock[p.id]??0)===0).length,recent:orders.slice(0,5)}}}
export const adminOrdersService={all:()=>employeeOrdersService.all(),update:(order:ProOrder,update:AdminOrderUpdate)=>{const next={...order,...update,history:update.status&&update.status!==order.status?[...order.history,{status:update.status,date:now()}]:order.history};employeeOrdersService.save(next);audit('Mise à jour de',next.id);return next}}
export const adminEmployeeService={all:()=>storage.get<AdminEmployee[]>(key.employees,seedEmployees),save:(employee:AdminEmployee)=>{const all=adminEmployeeService.all();storage.set(key.employees,all.some(item=>item.id===employee.id)?all.map(item=>item.id===employee.id?employee:item):[employee,...all]);audit('Mise à jour de',`${employee.firstName} ${employee.lastName}`)},remove:(employee:AdminEmployee)=>{storage.set(key.employees,adminEmployeeService.all().filter(item=>item.id!==employee.id));adminArchiveService.add({id:employee.id,type:'employee',label:`${employee.firstName} ${employee.lastName}`,date:now()});audit('Archivage de',`${employee.firstName} ${employee.lastName}`)}}
export const adminInventoryService={stock:()=>employeeInventoryService.get(),movements:()=>employeeInventoryService.moves(),adjust:(productId:string,quantity:number,reason:string)=>{const item=employeeInventoryService.change(productId,quantity,quantity>=0?'in':'out',reason,'Rachid Admin');audit('Ajustement du stock',productId);return item}}
export const adminPosService={all:()=>employeePosService.all()}
export const adminSavService={all:()=>employeeSavService.all(),update:(request:ProSav)=>{employeeSavService.save(request);audit('Mise à jour SAV',request.id)}}
export const adminMessagingService={all:()=>employeeMessagingService.all(),send:(body:string)=>{employeeMessagingService.send(body);audit('Message interne','Équipe')}}
export const adminPublicSiteService={get:()=>storage.get<AdminSettings>(key.settings,defaultSettings),save:(settings:AdminSettings)=>{storage.set(key.settings,settings);audit('Mise à jour','Apparence du site')}}
export const adminSupplierService={all:()=>storage.get<AdminSupplier[]>(key.suppliers,seedSuppliers),save:(supplier:AdminSupplier)=>{const all=adminSupplierService.all();storage.set(key.suppliers,all.some(item=>item.id===supplier.id)?all.map(item=>item.id===supplier.id?supplier:item):[supplier,...all]);audit('Mise à jour fournisseur',supplier.name)}}
export const adminPurchaseService={all:()=>storage.get<AdminPurchase[]>(key.purchases,seedPurchases),save:(purchase:AdminPurchase)=>{const all=adminPurchaseService.all();storage.set(key.purchases,all.some(item=>item.id===purchase.id)?all.map(item=>item.id===purchase.id?purchase:item):[purchase,...all]);audit('Mise à jour achat',purchase.id)},receive:(purchase:AdminPurchase)=>{purchase.lines.forEach(line=>employeeInventoryService.change(line.productId,line.quantity,'in',`Réception ${purchase.id}`,'Rachid Admin'));adminPurchaseService.save({...purchase,status:'received'});audit('Réception achat',purchase.id)}}
export const adminSalaryService={all:()=>adminEmployeeService.all().map((employee,index)=>({employee,amount:[4200,4600,4500][index]??4000,paid:index!==2,month:'Octobre 2026'}))}
export const adminReportService={sales:()=>({orders:adminOrdersService.all(),sales:adminPosService.all(),generatedAt:now()}),print:()=>window.print()}
export const adminNotificationService={all:()=>storage.get<AdminNotification[]>(key.notes,[{id:'n1',title:'Stock à surveiller',body:'Des références sont proches du seuil minimum.',read:false,date:'Aujourd’hui · 09:20',level:'warning'},{id:'n2',title:'Commande confirmée',body:'ER-2026-001284 est prête à être préparée.',read:false,date:'Aujourd’hui · 10:05',level:'info'}]),readAll:()=>storage.set(key.notes,adminNotificationService.all().map(item=>({...item,read:true})))}
export const adminAuditService={all:()=>storage.get<AdminAudit[]>(key.audit,[])}
export const adminArchiveService={all:()=>storage.get<AdminArchiveItem[]>(key.archive,[]),add:(item:AdminArchiveItem)=>storage.set(key.archive,[item,...adminArchiveService.all()]),restore:(id:string)=>storage.set(key.archive,adminArchiveService.all().filter(item=>item.id!==id))}
export const adminSettingsService={get:adminPublicSiteService.get,save:adminPublicSiteService.save}
