import {products} from '../data/mock'
import type {EmployeeProfile,PosSale,ProMessage,ProOrder,ProOrderStatus,ProSav,SalaryRecord,StockMovement} from '../types/employee'
import {storage} from './storage'

const key={session:'er-pro-session',locale:'er-pro-locale',orders:'er-pro-orders',stock:'er-pro-stock',sales:'er-pro-sales',sav:'er-pro-sav',messages:'er-pro-messages',moves:'er-pro-moves'}
const profiles:Record<string,EmployeeProfile>={amina:{id:'emp-a',firstName:'Amina',lastName:'Rachid',position:'Vendeuse',hours:'Lundi – Vendredi · 09:00 – 18:00',permissions:['orders']},youssef:{id:'emp-b',firstName:'Youssef',lastName:'El Mansouri',position:'Polyvalent',hours:'Lundi – Samedi · 10:00 – 19:00',permissions:['products_view','stock_view','stock_edit','pos']},salma:{id:'emp-c',firstName:'Salma',lastName:'Bennani',position:'SAV',hours:'Lundi – Vendredi · 09:00 – 18:00',permissions:['sav']}}
const seedOrders:ProOrder[]=[{id:'ER-2026-001284',assigneeId:'emp-a',client:'Nadia El Idrissi',phone:'+212 6 18 52 44 10',address:'12, rue Al Massira, Ain Al Aouda',date:'03/10/2026',total:1299,delivery:'delivery',payment:'card',status:'confirmed',items:[{productId:'af55',quantity:1,price:1299}],history:[{status:'new',date:'03/10/2026 · 09:12'},{status:'confirmed',date:'03/10/2026 · 10:05'}]},{id:'ER-2026-001279',assigneeId:'emp-a',client:'Omar Bensalem',phone:'+212 6 44 82 19 02',date:'02/10/2026',total:790,delivery:'pickup',payment:'cash',status:'ready',items:[{productId:'st24',quantity:1,price:790}],history:[{status:'new',date:'02/10/2026 · 11:10'},{status:'preparing',date:'02/10/2026 · 11:24'},{status:'ready',date:'02/10/2026 · 14:08'}]},{id:'ER-2026-001267',assigneeId:'emp-z',client:'Hassan Ait Ali',phone:'+212 6 55 10 33 20',date:'01/10/2026',total:549,delivery:'delivery',payment:'transfer',status:'preparing',items:[{productId:'kt17',quantity:1,price:549}],history:[{status:'new',date:'01/10/2026 · 15:22'}]}]
const seedSav:ProSav[]=[{id:'SAV-2026-014',client:'Lina Azzouzi',productId:'cf10',orderId:'ER-2026-001210',date:'01/10/2026',status:'processing',description:'La cafetière ne démarre plus.',notes:['Produit reçu au comptoir.']},{id:'SAV-2026-011',client:'Mounir Idrissi',productId:'mx45',orderId:'ER-2026-001196',date:'29/09/2026',status:'waiting',description:'Bruit anormal pendant le pétrissage.',notes:['En attente du diagnostic fournisseur.']}]
const seedMessages:ProMessage[]=[{id:'m1',sender:'direction',body:'Bonjour Amina, merci de confirmer les commandes du matin avant 11 h.',date:'Aujourd’hui · 08:42',read:false},{id:'m2',sender:'employee',body:'Bien reçu, je m’en occupe.',date:'Hier · 17:10',read:true}]
export const employeeAuthService={get:()=>storage.get<EmployeeProfile|null>(key.session,null),login:(firstName:string,lastName:string)=>{const profile=profiles[firstName.trim().toLowerCase()]??{...profiles.amina,firstName:firstName||'Amina',lastName:lastName||'Rachid'};storage.set(key.session,profile);return profile},logout:()=>storage.remove(key.session)}
export const employeeLocaleService={get:()=>storage.get<'fr'|'ar'>(key.locale,'fr'),set:(locale:'fr'|'ar')=>storage.set(key.locale,locale)}
export const employeeOrdersService={all:()=>storage.get<ProOrder[]>(key.orders,seedOrders),mine:(id:string)=>employeeOrdersService.all().filter(order=>order.assigneeId===id),save:(order:ProOrder)=>storage.set(key.orders,employeeOrdersService.all().map(item=>item.id===order.id?order:item)),transition:(order:ProOrder,status:ProOrderStatus)=>employeeOrdersService.save({...order,status,history:[...order.history,{status,date:new Date().toLocaleString('fr-MA')}]})}
export const employeeInventoryService={get:()=>storage.get<Record<string,number>>(key.stock,Object.fromEntries(products.map(product=>[product.id,product.stock]))),change:(productId:string,quantity:number,kind:StockMovement['kind'],reason:string,employee:string)=>{const stock=employeeInventoryService.get();storage.set(key.stock,{...stock,[productId]:Math.max(0,(stock[productId]??0)+quantity)});const move:StockMovement={id:crypto.randomUUID(),productId,quantity,kind,reason,date:new Date().toLocaleString('fr-MA'),employee};storage.set(key.moves,[move,...storage.get<StockMovement[]>(key.moves,[])]);return move},moves:()=>storage.get<StockMovement[]>(key.moves,[])}
export const employeePosService={all:()=>storage.get<PosSale[]>(key.sales,[]),save:(sale:PosSale)=>storage.set(key.sales,[sale,...employeePosService.all()])}
export const employeeSavService={all:()=>storage.get<ProSav[]>(key.sav,seedSav),save:(request:ProSav)=>storage.set(key.sav,employeeSavService.all().map(item=>item.id===request.id?request:item))}
export const employeeMessagingService={all:()=>storage.get<ProMessage[]>(key.messages,seedMessages),send:(body:string)=>storage.set(key.messages,[...employeeMessagingService.all(),{id:crypto.randomUUID(),sender:'employee',body,date:'À l’instant',read:true}]),read:()=>storage.set(key.messages,employeeMessagingService.all().map(message=>({...message,read:true})))}
export const employeeSalaryService={all:():SalaryRecord[]=>[{month:'Janvier',amount:3500,paid:true},{month:'Février',amount:3500,paid:true},{month:'Mars',amount:3500,paid:false}]}
