import {initialNotifications,products} from '../data/mock';import type {Address,Cart,CartItem,Customer,Locale,Notification,Order,Product,Session} from '../types';import {storage} from './storage'
const keys={cart:'er-cart',session:'er-session',favorites:'er-favorites',addresses:'er-addresses',orders:'er-orders',notifications:'er-notifications',locale:'er-locale'}
export const productService={getAll:async():Promise<Product[]>=>products,getBySlug:async(slug:string)=>products.find(p=>p.slug===slug),search:async(query:string)=>products.filter(p=>Object.values(p.name).join(' ').toLowerCase().includes(query.toLowerCase())||p.reference.toLowerCase().includes(query.toLowerCase()))}
export const cartService={get:():Cart=>storage.get<Cart>(keys.cart,{items:[]}),save:(cart:Cart)=>storage.set(keys.cart,cart),add:(item:CartItem)=>{const cart=cartService.get();const found=cart.items.find(x=>x.productId===item.productId&&x.variant===item.variant);cart.items=found?cart.items.map(x=>x===found?{...x,quantity:x.quantity+item.quantity}:x):[...cart.items,item];cartService.save(cart);return cart},update:(productId:string,quantity:number)=>{const cart=cartService.get();cart.items=cart.items.map(x=>x.productId===productId?{...x,quantity}:x).filter(x=>x.quantity>0);cartService.save(cart);return cart},remove:(productId:string)=>cartService.update(productId,0),clear:()=>cartService.save({items:[]})}
export const authService={getSession:():Session=>storage.get<Session>(keys.session,null),login:(email:string)=>{const customer:Customer={firstName:'Amina',lastName:'Rachid',email,phone:'+212 6 12 34 56 78',marketing:false};storage.set(keys.session,{customer});return {customer}},register:(customer:Customer)=>{storage.set(keys.session,{customer});return {customer}},logout:()=>storage.remove(keys.session)}
export const accountService={update:(customer:Customer)=>storage.set(keys.session,{customer}),getAddresses:()=>storage.get<Address[]>(keys.addresses,[{id:'a1',label:'Maison',city:'Ain Al Aouda',line:'24, rue Al Massira',isDefault:true}]),saveAddresses:(v:Address[])=>storage.set(keys.addresses,v)}
export const favoritesService={get:()=>storage.get<string[]>(keys.favorites,[]),toggle:(id:string)=>{const list=favoritesService.get();const next=list.includes(id)?list.filter(x=>x!==id):[...list,id];storage.set(keys.favorites,next);return next}}
export const orderService={getAll:()=>storage.get<Order[]>(keys.orders,[{id:'ER-2026-001234',trackingCode:'ER-7K4P-92XM',date:'2026-10-02',status:'preparing',delivery:'delivery',payment:'cash',items:[{productId:'af55',quantity:1,price:1299}],total:1299}]),save:(order:Order)=>{const all=orderService.getAll();storage.set(keys.orders,[order,...all])},track:(code:string,contact:string)=>code==='ER-7K4P-92XM'&&contact.length>4?orderService.getAll()[0]:undefined}
export const trackingService={track:orderService.track};export const recommendationService={get:async()=>products.filter(p=>p.popular).slice(0,4)}
export const notificationService={get:()=>storage.get<Notification[]>(keys.notifications,initialNotifications),markRead:(id:string)=>storage.set(keys.notifications,notificationService.get().map(n=>n.id===id?{...n,read:true}:n))}
export const localeService={get:():Locale=>storage.get<Locale>(keys.locale,navigator.language.startsWith('ar')?'ar':'fr'),set:(locale:Locale)=>storage.set(keys.locale,locale)}
